name: PSS-SEPLAG
# Banco de Dados (PostgreSQL - alpine)
services:
  postgres:
    image: postgres:15-alpine
    container_name: BancoDeDados
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - seplag-network


  # MinIO (Armazenamento de Imagens)
  minio:
    image: minio/minio:latest
    container_name: MinIO
    command: server /data --console-address ":9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"   # Olhar nota 2 no final do arquivo.
      - "9001:9001"   # Olhar nota 3 no final do arquivo.
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - seplag-network

volumes:
  postgres_db:
  minio_data:

networks:
  seplag-network:
    driver: bridge

#Notas: 
# 1. Vari√°veis de ambiente carregadas do arquivo .env
# 2. Porta da API
# 3. Porta do Console Web